### ISSUE TITLE
Option to download only non-synced lyrics

### ISSUE THREAD

**Issue by TT-ReBORN** [ESLyric/feedback#76]
Hi ohyeah,

a user of mine asked if you could add an option to download only non-synced lyrics ( txt ).
In ESLyric main preferences there is an fallback option to "Always prefer synced lyrics",
can you add the option "Always use non-synced lyrics" ?

Thanks!

-TT

**Comment by ESLyric** [comment]
can you use non-synced lyric source only?

**Comment by TT-ReBORN** [comment]
Do you mean the user should select sources that are non-synced only?
I have all sources enabled in my theme, which sources are non-synced only?
I thought all lyrics servers have both, synced ( if available ) and non-synced ( standard, mostly always available )
so that could be a problem and also confusing for the user.

**Comment by a1waysbeta** [comment]
The three lyrics sources of KG QQ NT are all Chinese servers, generally there are no asynchronous lyrics, and the rest of the lyrics sources should have asynchronous lyrics. Or just look for new lyrics source api, help write lyrics source script, such as itunes server...

**Comment by TT-ReBORN** [comment]
I thought it wouldn't be a problem to implement an option to fetch only .txt ( non-synced ) lyric files and not .lrc ( synced ) lyrics from the servers/lyric sources via search query, this is what a user from my theme was asking. He only wants to have non-synced lyric files as .txt files and does not want any .lrc synced lyrics on his HDD.

**Comment by ESLyric** [comment]
just enable 'Genius' and 'AZLyric'.

**Comment by a1waysbeta** [comment]
First of all, ESL does not have its own lyrics server. The synced and non-synced lyrics often depend on the existing lyrics source. Among them, Kugou Music (similar to last.fm) in order to attract users, the app publicity: the lyrics are accurately synchronized, with translate...Maybe there are no asynchronous lyrics on their servers at all.
As an aside, you can try to use ESL directly to display lyrics instead of SMP on Georgia-ReBORN, and its effect is just as amazing. You can even try ESL's layout function, and you can save an SMP panel. With wilb's Bio artist image download function, the background image will play in a loop.
![动画2](https://user-images.githubusercontent.com/11453148/220833171-a1d6d074-8cdd-4a56-a831-7319f4bb239c.gif)
https://imgur.com/a/TQlmnDY

**Comment by TT-ReBORN** [comment]
The new lyric source pack has enough unsynced sources now:
https://github.com/ESLyric/feedback/issues/115

I'm marking this as finished and closing.
